### ISSUE TITLE
Unsupported configuration type: NULL

### ISSUE THREAD

**Issue by wispoz** [paulzi/yii2-materialized-path#12]
`    public function behaviors() {
        return [
            [
            'class' => MaterializedPathBehavior::className(),
            'pathAttribute' =>'UF_PATH',
            'depthAttribute' =>'UF_DEPTH',
            'sortable' =>'UF_SORT',

```
        ],
    ];
}
```

`
cause error:
`Invalid Configuration – yii\base\InvalidConfigException
Unsupported configuration type: NULL`

**Comment by paulzi** [comment]
In version 2.0 `sortable` field is config for `SortableBehavior`. Use:

``` php
public function behaviors() {
    return [
        [
            'class' => MaterializedPathBehavior::className(),
            'pathAttribute' =>'UF_PATH',
            'depthAttribute' =>'UF_DEPTH',
            'sortable' =>['sortAttribute' => 'UF_SORT'],
        ],
    ];
}
```
