### ISSUE TITLE
Simple rename node

### ISSUE THREAD

**Issue by xvs32x** [paulzi/yii2-materialized-path#13]
After change name of node, deth property get extra slash in begining
example

```
      $model = $this->findModel($id); 
      $model->name = 'Node 1';  
      $model->save();  
```

After this manipulation I have " path='/54/53' "

**Comment by paulzi** [comment]
Please provide the code of attach behavior and the table schema.

**Comment by xvs32x** [comment]
I'm sorry I certainly mixed properties, I mean **path** property that stores the path to the node. I corrected the first message.

```
public function actionRenamePath($id){
    /** @var \app\modules\file\models\Path $modelClass*/
    $model = $this->findPath($id);

    $model->name = Yii::$app->request->post('name');
    if ($model->save() === false && !$model->hasErrors()) {
        throw new ServerErrorHttpException('Failed to update the object for unknown reason.');
    }

    return $model;
}

/*Model*/
public function behaviors()
{
    return [
        [
            'class' => MaterializedPathBehavior::className(),
            'treeAttribute' => 'tree',
        ],
    ];
}

  /*Migration*/
  public function up()
{
    $tableOptions = null;
    if ($this->db->driverName === 'mysql') {
        // http://stackoverflow.com/questions/766809/whats-the-difference-between-utf8-general-ci-and-utf8-unicode-ci
        $tableOptions = 'CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE=InnoDB';
    }
    $this->createTable('{{%path}}', [
        'id'    => Schema::TYPE_PK,
        'tree'  => Schema::TYPE_BIGINT . ' NULL',
        'path'  => Schema::TYPE_STRING . ' NULL',
        'depth' => Schema::TYPE_INTEGER . ' NOT NULL',
        'sort'  => Schema::TYPE_INTEGER . ' NOT NULL',
        'name'  => Schema::TYPE_STRING . ' NOT NULL',
    ], $tableOptions);
    $this->createIndex('tree_path', '{{%path}}', ['tree', 'path']);
}
```

**Comment by paulzi** [comment]
Please provide code of Path::rules(). I think that the error occurs because of a validation.
For check, you can try `->save (false)`.

**Comment by paulzi** [comment]
I create branch `issue-13` with demo that the behavior works as expected.
Please check your code (validation rules).

``` bash
git clone https://github.com/paulzi/yii2-materialized-path.git
git checkout issue-13
composer update --prefer-dist
phpunit
```

Test:

``` php
    public function testGetParents()
    {
        $model = Path::findOne(9);
        $model->name = 'test';
        $model->save();
        $model = Path::findOne(9);
        $this->assertEquals('1/3/9', $model->path);
        $this->assertEquals('test', $model->name);
    }
```

Output:

```
PHPUnit 4.8.7 by Sebastian Bergmann and contributors.

.

Time: 558 ms, Memory: 17.25Mb

OK (1 test, 2 assertions)
```

**Comment by xvs32x** [comment]
This solution ->save (false) is not helped for me. I commented this lines in hebavior(beforeSave method) and save() method work correctly:

```
            if ($this->owner->getIsNewRecord()) {
                throw new NotSupportedException('Method "' . $this->owner->className() . '::insert" is not supported for inserting new nodes.');
            }

            $item = $this->owner->getAttribute($this->itemAttribute);
            $path = $this->getParentPath();
            $this->owner->setAttribute($this->pathAttribute, $path . $this->delimiter . $item);
```

My environment:
Postgres 9.5.2
PHP 7.0.4

I think problem in this line:
`$this->owner->setAttribute($this->pathAttribute, $path . $this->delimiter . $item);`

**Comment by paulzi** [comment]
What returns this code?

``` php
$model = $this->findPath($id);
var_dump($model->path);
```

You tried to run phpunit in branch issue-13?

**Comment by xvs32x** [comment]
Excuse me, could you describe in more detail the testing process? I just have not yet learned unit testing
I have a clarification. This only occurs when editing root node
$model dump: 

`
object(app\modules\file\models\Path)#124 (8) {
  ["_attributes":"yii\db\BaseActiveRecord":private]=>
  array(6) {
    ["id"]=>
    int(88)
    ["tree"]=>
    int(88)
    ["path"]=>
    string(3) "/88"
    ["depth"]=>
    int(0)
    ["sort"]=>
    int(0)
    ["name"]=>
    string(21) "Some folder - renamed"
  }
  ["_oldAttributes":"yii\db\BaseActiveRecord":private]=>
  array(6) {
    ["id"]=>
    int(88)
    ["tree"]=>
    int(88)
    ["path"]=>
    string(3) "/88"
    ["depth"]=>
    int(0)
    ["sort"]=>
    int(0)
    ["name"]=>
    string(21) "Some folder - renamed"
  }
  ["_related":"yii\db\BaseActiveRecord":private]=>
  array(0) {
  }
  ["_errors":"yii\base\Model":private]=>
  NULL
  ["_validators":"yii\base\Model":private]=>
  NULL
  ["_scenario":"yii\base\Model":private]=>
  string(7) "default"
  ["_events":"yii\base\Component":private]=>
  array(6) {
    ["beforeInsert"]=>
    array(2) {
      [0]=>
      array(2) {
        [0]=>
        array(2) {
          [0]=>
          object(paulzi\materializedPath\MaterializedPathBehavior)#128 (12) {
            ["pathAttribute"]=>
            string(4) "path"
            ["depthAttribute"]=>
            string(5) "depth"
            ["itemAttribute"]=>
            string(2) "id"
            ["treeAttribute"]=>
            string(4) "tree"
            ["sortable"]=>
            array(0) {
            }
            ["delimiter"]=>
            string(1) "/"
            ["rootDepthValue"]=>
            int(0)
            ["operation":protected]=>
            NULL
            ["node":protected]=>
            NULL
            ["behavior":protected]=>
            object(paulzi\sortable\SortableBehavior)#139 (8) {
              ["query"]=>
              object(Closure)#136 (1) {
                ["this"]=>
                *RECURSION*
              }
              ["sortAttribute"]=>
              string(4) "sort"
              ["step"]=>
              int(100)
              ["joinMode"]=>
              bool(true)
              ["windowSize"]=>
              int(1000)
              ["operation":protected]=>
              NULL
              ["position":protected]=>
              NULL
              ["owner"]=>
              *RECURSION*
            }
            ["primaryKeyMode":protected]=>
            bool(true)
            ["owner"]=>
            *RECURSION*
          }
          [1]=>
          string(10) "beforeSave"
        }
        [1]=>
        NULL
      }
      [1]=>
      array(2) {
        [0]=>
        array(2) {
          [0]=>
          object(paulzi\sortable\SortableBehavior)#139 (8) {
            ["query"]=>
            object(Closure)#136 (1) {
              ["this"]=>
              object(paulzi\materializedPath\MaterializedPathBehavior)#128 (12) {
                ["pathAttribute"]=>
                string(4) "path"
                ["depthAttribute"]=>
                string(5) "depth"
                ["itemAttribute"]=>
                string(2) "id"
                ["treeAttribute"]=>
                string(4) "tree"
                ["sortable"]=>
                array(0) {
                }
                ["delimiter"]=>
                string(1) "/"
                ["rootDepthValue"]=>
                int(0)
                ["operation":protected]=>
                NULL
                ["node":protected]=>
                NULL
                ["behavior":protected]=>
                *RECURSION*
                ["primaryKeyMode":protected]=>
                bool(true)
                ["owner"]=>
                *RECURSION*
              }
            }
            ["sortAttribute"]=>
            string(4) "sort"
            ["step"]=>
            int(100)
            ["joinMode"]=>
            bool(true)
            ["windowSize"]=>
            int(1000)
            ["operation":protected]=>
            NULL
            ["position":protected]=>
            NULL
            ["owner"]=>
            *RECURSION*
          }
          [1]=>
          string(10) "beforeSave"
        }
        [1]=>
        NULL
      }
    }
    ["afterInsert"]=>
    array(2) {
      [0]=>
      array(2) {
        [0]=>
        array(2) {
          [0]=>
          object(paulzi\materializedPath\MaterializedPathBehavior)#128 (12) {
            ["pathAttribute"]=>
            string(4) "path"
            ["depthAttribute"]=>
            string(5) "depth"
            ["itemAttribute"]=>
            string(2) "id"
            ["treeAttribute"]=>
            string(4) "tree"
            ["sortable"]=>
            array(0) {
            }
            ["delimiter"]=>
            string(1) "/"
            ["rootDepthValue"]=>
            int(0)
            ["operation":protected]=>
            NULL
            ["node":protected]=>
            NULL
            ["behavior":protected]=>
            object(paulzi\sortable\SortableBehavior)#139 (8) {
              ["query"]=>
              object(Closure)#136 (1) {
                ["this"]=>
                *RECURSION*
              }
              ["sortAttribute"]=>
              string(4) "sort"
              ["step"]=>
              int(100)
              ["joinMode"]=>
              bool(true)
              ["windowSize"]=>
              int(1000)
              ["operation":protected]=>
              NULL
              ["position":protected]=>
              NULL
              ["owner"]=>
              *RECURSION*
            }
            ["primaryKeyMode":protected]=>
            bool(true)
            ["owner"]=>
            *RECURSION*
          }
          [1]=>
          string(11) "afterInsert"
        }
        [1]=>
        NULL
      }
      [1]=>
      array(2) {
        [0]=>
        array(2) {
          [0]=>
          object(paulzi\sortable\SortableBehavior)#139 (8) {
            ["query"]=>
            object(Closure)#136 (1) {
              ["this"]=>
              object(paulzi\materializedPath\MaterializedPathBehavior)#128 (12) {
                ["pathAttribute"]=>
                string(4) "path"
                ["depthAttribute"]=>
                string(5) "depth"
                ["itemAttribute"]=>
                string(2) "id"
                ["treeAttribute"]=>
                string(4) "tree"
                ["sortable"]=>
                array(0) {
                }
                ["delimiter"]=>
                string(1) "/"
                ["rootDepthValue"]=>
                int(0)
                ["operation":protected]=>
                NULL
                ["node":protected]=>
                NULL
                ["behavior":protected]=>
                *RECURSION*
                ["primaryKeyMode":protected]=>
                bool(true)
                ["owner"]=>
                *RECURSION*
              }
            }
            ["sortAttribute"]=>
            string(4) "sort"
            ["step"]=>
            int(100)
            ["joinMode"]=>
            bool(true)
            ["windowSize"]=>
            int(1000)
            ["operation":protected]=>
            NULL
            ["position":protected]=>
            NULL
            ["owner"]=>
            *RECURSION*
          }
          [1]=>
          string(9) "afterSave"
        }
        [1]=>
        NULL
      }
    }
    ["beforeUpdate"]=>
    array(2) {
      [0]=>
      array(2) {
        [0]=>
        array(2) {
          [0]=>
          object(paulzi\materializedPath\MaterializedPathBehavior)#128 (12) {
            ["pathAttribute"]=>
            string(4) "path"
            ["depthAttribute"]=>
            string(5) "depth"
            ["itemAttribute"]=>
            string(2) "id"
            ["treeAttribute"]=>
            string(4) "tree"
            ["sortable"]=>
            array(0) {
            }
            ["delimiter"]=>
            string(1) "/"
            ["rootDepthValue"]=>
            int(0)
            ["operation":protected]=>
            NULL
            ["node":protected]=>
            NULL
            ["behavior":protected]=>
            object(paulzi\sortable\SortableBehavior)#139 (8) {
              ["query"]=>
              object(Closure)#136 (1) {
                ["this"]=>
                *RECURSION*
              }
              ["sortAttribute"]=>
              string(4) "sort"
              ["step"]=>
              int(100)
              ["joinMode"]=>
              bool(true)
              ["windowSize"]=>
              int(1000)
              ["operation":protected]=>
              NULL
              ["position":protected]=>
              NULL
              ["owner"]=>
              *RECURSION*
            }
            ["primaryKeyMode":protected]=>
            bool(true)
            ["owner"]=>
            *RECURSION*
          }
          [1]=>
          string(10) "beforeSave"
        }
        [1]=>
        NULL
      }
      [1]=>
      array(2) {
        [0]=>
        array(2) {
          [0]=>
          object(paulzi\sortable\SortableBehavior)#139 (8) {
            ["query"]=>
            object(Closure)#136 (1) {
              ["this"]=>
              object(paulzi\materializedPath\MaterializedPathBehavior)#128 (12) {
                ["pathAttribute"]=>
                string(4) "path"
                ["depthAttribute"]=>
                string(5) "depth"
                ["itemAttribute"]=>
                string(2) "id"
                ["treeAttribute"]=>
                string(4) "tree"
                ["sortable"]=>
                array(0) {
                }
                ["delimiter"]=>
                string(1) "/"
                ["rootDepthValue"]=>
                int(0)
                ["operation":protected]=>
                NULL
                ["node":protected]=>
                NULL
                ["behavior":protected]=>
                *RECURSION*
                ["primaryKeyMode":protected]=>
                bool(true)
                ["owner"]=>
                *RECURSION*
              }
            }
            ["sortAttribute"]=>
            string(4) "sort"
            ["step"]=>
            int(100)
            ["joinMode"]=>
            bool(true)
            ["windowSize"]=>
            int(1000)
            ["operation":protected]=>
            NULL
            ["position":protected]=>
            NULL
            ["owner"]=>
            *RECURSION*
          }
          [1]=>
          string(10) "beforeSave"
        }
        [1]=>
        NULL
      }
    }
    ["afterUpdate"]=>
    array(2) {
      [0]=>
      array(2) {
        [0]=>
        array(2) {
          [0]=>
          object(paulzi\materializedPath\MaterializedPathBehavior)#128 (12) {
            ["pathAttribute"]=>
            string(4) "path"
            ["depthAttribute"]=>
            string(5) "depth"
            ["itemAttribute"]=>
            string(2) "id"
            ["treeAttribute"]=>
            string(4) "tree"
            ["sortable"]=>
            array(0) {
            }
            ["delimiter"]=>
            string(1) "/"
            ["rootDepthValue"]=>
            int(0)
            ["operation":protected]=>
            NULL
            ["node":protected]=>
            NULL
            ["behavior":protected]=>
            object(paulzi\sortable\SortableBehavior)#139 (8) {
              ["query"]=>
              object(Closure)#136 (1) {
                ["this"]=>
                *RECURSION*
              }
              ["sortAttribute"]=>
              string(4) "sort"
              ["step"]=>
              int(100)
              ["joinMode"]=>
              bool(true)
              ["windowSize"]=>
              int(1000)
              ["operation":protected]=>
              NULL
              ["position":protected]=>
              NULL
              ["owner"]=>
              *RECURSION*
            }
            ["primaryKeyMode":protected]=>
            bool(true)
            ["owner"]=>
            *RECURSION*
          }
          [1]=>
          string(11) "afterUpdate"
        }
        [1]=>
        NULL
      }
      [1]=>
      array(2) {
        [0]=>
        array(2) {
          [0]=>
          object(paulzi\sortable\SortableBehavior)#139 (8) {
            ["query"]=>
            object(Closure)#136 (1) {
              ["this"]=>
              object(paulzi\materializedPath\MaterializedPathBehavior)#128 (12) {
                ["pathAttribute"]=>
                string(4) "path"
                ["depthAttribute"]=>
                string(5) "depth"
                ["itemAttribute"]=>
                string(2) "id"
                ["treeAttribute"]=>
                string(4) "tree"
                ["sortable"]=>
                array(0) {
                }
                ["delimiter"]=>
                string(1) "/"
                ["rootDepthValue"]=>
                int(0)
                ["operation":protected]=>
                NULL
                ["node":protected]=>
                NULL
                ["behavior":protected]=>
                *RECURSION*
                ["primaryKeyMode":protected]=>
                bool(true)
                ["owner"]=>
                *RECURSION*
              }
            }
            ["sortAttribute"]=>
            string(4) "sort"
            ["step"]=>
            int(100)
            ["joinMode"]=>
            bool(true)
            ["windowSize"]=>
            int(1000)
            ["operation":protected]=>
            NULL
            ["position":protected]=>
            NULL
            ["owner"]=>
            *RECURSION*
          }
          [1]=>
          string(9) "afterSave"
        }
        [1]=>
        NULL
      }
    }
    ["beforeDelete"]=>
    array(1) {
      [0]=>
      array(2) {
        [0]=>
        array(2) {
          [0]=>
          object(paulzi\materializedPath\MaterializedPathBehavior)#128 (12) {
            ["pathAttribute"]=>
            string(4) "path"
            ["depthAttribute"]=>
            string(5) "depth"
            ["itemAttribute"]=>
            string(2) "id"
            ["treeAttribute"]=>
            string(4) "tree"
            ["sortable"]=>
            array(0) {
            }
            ["delimiter"]=>
            string(1) "/"
            ["rootDepthValue"]=>
            int(0)
            ["operation":protected]=>
            NULL
            ["node":protected]=>
            NULL
            ["behavior":protected]=>
            object(paulzi\sortable\SortableBehavior)#139 (8) {
              ["query"]=>
              object(Closure)#136 (1) {
                ["this"]=>
                *RECURSION*
              }
              ["sortAttribute"]=>
              string(4) "sort"
              ["step"]=>
              int(100)
              ["joinMode"]=>
              bool(true)
              ["windowSize"]=>
              int(1000)
              ["operation":protected]=>
              NULL
              ["position":protected]=>
              NULL
              ["owner"]=>
              *RECURSION*
            }
            ["primaryKeyMode":protected]=>
            bool(true)
            ["owner"]=>
            *RECURSION*
          }
          [1]=>
          string(12) "beforeDelete"
        }
        [1]=>
        NULL
      }
    }
    ["afterDelete"]=>
    array(1) {
      [0]=>
      array(2) {
        [0]=>
        array(2) {
          [0]=>
          object(paulzi\materializedPath\MaterializedPathBehavior)#128 (12) {
            ["pathAttribute"]=>
            string(4) "path"
            ["depthAttribute"]=>
            string(5) "depth"
            ["itemAttribute"]=>
            string(2) "id"
            ["treeAttribute"]=>
            string(4) "tree"
            ["sortable"]=>
            array(0) {
            }
            ["delimiter"]=>
            string(1) "/"
            ["rootDepthValue"]=>
            int(0)
            ["operation":protected]=>
            NULL
            ["node":protected]=>
            NULL
            ["behavior":protected]=>
            object(paulzi\sortable\SortableBehavior)#139 (8) {
              ["query"]=>
              object(Closure)#136 (1) {
                ["this"]=>
                *RECURSION*
              }
              ["sortAttribute"]=>
              string(4) "sort"
              ["step"]=>
              int(100)
              ["joinMode"]=>
              bool(true)
              ["windowSize"]=>
              int(1000)
              ["operation":protected]=>
              NULL
              ["position":protected]=>
              NULL
              ["owner"]=>
              *RECURSION*
            }
            ["primaryKeyMode":protected]=>
            bool(true)
            ["owner"]=>
            *RECURSION*
          }
          [1]=>
          string(11) "afterDelete"
        }
        [1]=>
        NULL
      }
    }
  }
  ["_behaviors":"yii\base\Component":private]=>
  array(2) {
    ["materialized-path-sortable"]=>
    object(paulzi\sortable\SortableBehavior)#139 (8) {
      ["query"]=>
      object(Closure)#136 (1) {
        ["this"]=>
        object(paulzi\materializedPath\MaterializedPathBehavior)#128 (12) {
          ["pathAttribute"]=>
          string(4) "path"
          ["depthAttribute"]=>
          string(5) "depth"
          ["itemAttribute"]=>
          string(2) "id"
          ["treeAttribute"]=>
          string(4) "tree"
          ["sortable"]=>
          array(0) {
          }
          ["delimiter"]=>
          string(1) "/"
          ["rootDepthValue"]=>
          int(0)
          ["operation":protected]=>
          NULL
          ["node":protected]=>
          NULL
          ["behavior":protected]=>
          *RECURSION*
          ["primaryKeyMode":protected]=>
          bool(true)
          ["owner"]=>
          *RECURSION*
        }
      }
      ["sortAttribute"]=>
      string(4) "sort"
      ["step"]=>
      int(100)
      ["joinMode"]=>
      bool(true)
      ["windowSize"]=>
      int(1000)
      ["operation":protected]=>
      NULL
      ["position":protected]=>
      NULL
      ["owner"]=>
      *RECURSION*
    }
    [0]=>
    object(paulzi\materializedPath\MaterializedPathBehavior)#128 (12) {
      ["pathAttribute"]=>
      string(4) "path"
      ["depthAttribute"]=>
      string(5) "depth"
      ["itemAttribute"]=>
      string(2) "id"
      ["treeAttribute"]=>
      string(4) "tree"
      ["sortable"]=>
      array(0) {
      }
      ["delimiter"]=>
      string(1) "/"
      ["rootDepthValue"]=>
      int(0)
      ["operation":protected]=>
      NULL
      ["node":protected]=>
      NULL
      ["behavior":protected]=>
      object(paulzi\sortable\SortableBehavior)#139 (8) {
        ["query"]=>
        object(Closure)#136 (1) {
          ["this"]=>
          *RECURSION*
        }
        ["sortAttribute"]=>
        string(4) "sort"
        ["step"]=>
        int(100)
        ["joinMode"]=>
        bool(true)
        ["windowSize"]=>
        int(1000)
        ["operation":protected]=>
        NULL
        ["position":protected]=>
        NULL
        ["owner"]=>
        *RECURSION*
      }
      ["primaryKeyMode":protected]=>
      bool(true)
      ["owner"]=>
      *RECURSION*
    }
  }
}
`

**Comment by xvs32x** [comment]
I think in this line 

`$this->owner->setAttribute($this->pathAttribute, $path . $this->delimiter . $item);`

Variable $path is empty because the root node not have parent node and script inserting only slash

**Comment by paulzi** [comment]
Your path attribute already wrong in dump:
`["path"]=> string(3) "/88"`

**Comment by paulzi** [comment]
The root node does not have a slash at the beginning of the path. Its path must be equal to its Id.
If you need other logic, you can set itemAttribute for other field.
By default itemAttribute is null, and behavior builds a path starting from the root key, without slash in beginning.

**Comment by xvs32x** [comment]
@paulzi This dump was made after the model changed

**Comment by xvs32x** [comment]
@paulzi Ok, I found problem, see code please. 
I brought the property values BEFORE change model, please see (the current value of the comments on the right)

```
            $item = $this->owner->getAttribute($this->itemAttribute);
            $path = $this->getParentPath();
            VarDumper::dump($item); // => 1
            VarDumper::dump($path); // => null
            VarDumper::dump($path . $this->delimiter . $item); // => /1
            $this->owner->setAttribute($this->pathAttribute, $path . $this->delimiter . $item);
```

> Если по русски, то скрипт пытается записать родителя ноды, но вместо родителя получает null(потому что у ноды нет родителя) и пишет как бы так 
> $this->owner->setAttribute($this->pathAttribute, null/1);

**Comment by paulzi** [comment]
I understand what the problem is. Now I prepare a fix.

> Понял, в чём проблема, сечас подготовлю фикс.

**Comment by paulzi** [comment]
Извини, сразу не врубился что речь о сохранении корневого узла.

**Comment by xvs32x** [comment]
@paulzi  Many thanks :)
