### ISSUE TITLE
populateTree considers andWhere condition?

### ISSUE THREAD

**Issue by wispoz** [paulzi/yii2-materialized-path#17]
I have 

``
$projectId =1;

$projectVersionId = 2; // various versions 1 - 100

$roots = Task::find()->roots()->andWhere(['project_id'=>$projectId,'project_version_id'=>$projectVersionId])->all();

foreach($roors as $root) {
$root->populateTree() // - will add to SQL where condition of project_version_id = 2 ?
}
``

**Comment by paulzi** [comment]
`populateTree()` get ALL descendants for node, and put them in relation `children`.
Conditions have ALREADY applied when selecting `$roots`.
