### ISSUE TITLE
Method "app\models\Category::delete" is not supported for deleting root nodes.

### ISSUE THREAD

**Issue by maxodrom** [paulzi/yii2-materialized-path#19]
Здравствуйте! 
Использую ваш behavior для работы с категориями в своих проектах.

Когда делаю так: 
```php
$deleted = $this->findModel($id)->deleteWithChildren();
```
удаление происходит нормально. Удаляется категория вместе с подкатегориями.

Когда же делаю так: 
```php
$deleted = $this->findModel($id)->delete();
```
возникает ошибка: Method "app\models\Category::delete" is not supported for deleting root nodes.

Почему такое происходит? Баг? Или я что-то делаю не так?

В документации у вас написано: 

```
To delete a node with descendants:

$node11 = Sample::findOne(['name' => 'node 1.1']);
$node11->delete(); // delete node, children come up to the parent
$node11->deleteWithChildren(); // delete node and all descendants 
```

Такая же ошибка выпадает, когда я пытаюсь полностью стереть каталог со всеми категориями и делаю это таким образом: 

```php
$targetProjectTreeQuery =
    Category::find()
        ->projectIs($targetProject->id)
        ->orderBy([
            'path' => SORT_DESC,
        ]);
/** @var \app\models\Category $targetProjectCategory */
foreach ($targetProjectTreeQuery->each() as $targetProjectCategory) {
    $targetProjectCategory->delete();
}
```

**Comment by paulzi** [comment]
Добрый день, всё написано в тексте ошибки:
`is not supported for deleting root nodes`
То есть корень нельзя «просто» удалить с перемещением детей к родителю, т. к. если у него есть дочерние элементы, их некуда перемещать, и все дети должны становиться корнями.
Корень можно удалить только методом `deleteWithChildren`.

> полностью стереть каталог со всеми категориями и делаю это таким образом

Опять же, почему не используется `deleteWithChildren`?
