### ISSUE TITLE
Namespace code style

### ISSUE THREAD

**Issue by arogachev** [paulzi/yii2-materialized-path#2]
I suggest change this part: `materializedpath` to this: `materializedPath`. It's more readable, don't cause notice messages in IDE (since it treats this phrase as one single word and it is a single word). Earlier I adviced with @samdark and he said that this is the better option. However @creocoder for example uses single word option.

Related Yii2 issue - yiisoft/yii2#8398

**Comment by samdark** [comment]
Both are PSR-2 comatible. In the Yii we're using only single words because it allows us to come up with better names. Writing two words as a single work doesn't make sense.
