### ISSUE TITLE
May be add method getTree()?

### ISSUE THREAD

**Issue by HaruAtari** [paulzi/yii2-materialized-path#7]
Get the complete tree of descendants - a common task when working with hierarchical structures. Is it possible to add method `getTree($depth = null)` that works same as `getDescendants()` but returns tree instead plain list? I mean this will be very useful, but this method returns not `ActiveQuery` as other methods.
What do you think about that?

**Comment by paulzi** [comment]
getDescendants() work as relation. If you need plain list of descendants (not ActiveQuery), simple use getter from model:
$descendants = $model->descendants;

**Comment by paulzi** [comment]
Sorry, I did not understand right away. Looks good.

**Comment by HaruAtari** [comment]
Good. I'll add this.

**Comment by paulzi** [comment]
I thought about this functionality, and can not think of the normal structure to return the result.
I believe that the structure in the form of:

``` php
$result = [
    [
        'item' => $model,
        'children' => [/* ... recoursive ... */],
    ],
    [
        'item' => $model,
        'children' => [/* ... recoursive ... */],
    ],
    /* ... more ... */
];
$title = $result[1]['children'][2]['item']->title;
```

bad idea, it's better this way to access:

``` php
$title = $model->children[1]->children[2]->title;
```

**Comment by HaruAtari** [comment]
We can set children for node by [\yii\db\BaseActiveRecord::populateRelation()](http://www.yiiframework.com/doc-2.0/yii-db-baseactiverecord.html#populateRelation%28%29-detail). And after that we can get childrend of node by using `$parent->children`.

**Comment by paulzi** [comment]
Good idea!

**Comment by HaruAtari** [comment]
Should this method returns self node as tree's root? Or he must returns list of next level children?  What code is prefered?

```
$node = Model::find()->byId(1)->one();
$tree = $node->getTree(); // $tree is same as $node but with children
$children = $tree->children;
```

or this:

```
$node = Model::find()->byId(1)->one();
$children = $node->getTree();
```

**Comment by paulzi** [comment]
I think that it should return itself. And we can rename getTree() to populateTree().
